### ISSUE TITLE
Where does `try` come from?

### ISSUE THREAD

**Issue by wlangstroth** [cl-facts/facts#1]
https://github.com/thodg/facts/blob/8c1cc4ea586fa33e5c1324f9abb01e821b4b2ef8/anon.lisp#L33

Can't find any other reference to `try`. Do you have it defined in a different package?

**Comment by thodg** [comment]
This was fixed in a later commit, see https://github.com/cl-facts/facts/commit/3b8bd17bb0bd67d36342a53f1cfc6abd62e4dc7e#diff-68bf1e95fed82411fb17bb65a83caf55
