### ISSUE TITLE
Any additional documentation 

### ISSUE THREAD

**Issue by Outstep** [cl-facts/facts#2]
Hello,

I just came across "facts" and am getting back into Lisp after many years for an AI project that I think would be a good compatible system and facts may work well for that also.

With this in mind, do you have any startup/loading instructions as I think that I will be using sbcl perhaps.

Also, maybe a couple more examples since what I need to figure out is how to setup various tags.

For example, if I have a "ball" object then different attributes could be "shape: round", "color: blue", etc... and then have a other objects that may have these attributes as well as additional ones.  Then, I will query "facts" for certain things to build arbitrary vectors that will be clustered by the AI software to classify similar attributes.

With all of this in mind, I need a graph database to help keep track of the attributes that will make up the vectors and which will be cross linked to other graph database nodes as well.

Any help will getting "facts" running and its usage vai more examples would be greatly appreciated.
Thanks

**Comment by thodg** [comment]
The README.md file was updated, please see https://github.com/cl-facts/facts
