### ISSUE TITLE
Add facts to UltraLisp

### ISSUE THREAD

**Issue by starcrATI** [cl-facts/facts#3]
Facts looks like a really cool library, and I would like to try it out.
Would be awesome if it would be available on [UltraLisp](https://ultralisp.org/).

**Comment by thodg** [comment]
Sure, I'm taking care of it.

**Comment by thodg** [comment]
That's 35 new packages from me.

**Comment by thodg** [comment]
https://ultralisp.org/versions/20200411180017

**Comment by starcrATI** [comment]
Awesome, thanks a lot!
